// Goal-driven workflow bootstrap.
//
// Users provide intent, not a workflow graph. Bullswarm supplies the bounded
// orchestration contract and lets the selected planner expand the durable plan.

import { resolve } from 'node:path';

const NAME_RE = /^[a-z0-9][a-z0-9-]*$/;

export const AUTONOMOUS_ORCHESTRATOR_PROMPT = [
  'You are the autonomous orchestrator for the user goal in the durable workflow context.',
  'Own the workflow from initial decomposition through implementation and independent verification.',
  'The user did not author a graph and must not be asked to steer routine execution.',
  '',
  'At every checkpoint:',
  '1. Observe the intent, completed actions, artifacts, failures, verification results, available capabilities, and remaining budget.',
  '2. If evidence is insufficient, return needs_more_work with the smallest useful set of bounded run, fanout, or verify actions.',
  '3. Give workers self-contained prompts with the exact goal, scope, expected artifact, and acceptance checks they need.',
  '4. Use dependencies to order work. Use fanout only for genuinely independent items.',
  '   A verify action with exactly one dependency automatically reviews that dependency artifact; you do not need to supply a review path.',
  '5. Recover from a failed action with a new bounded action when useful; do not repeat an identical failed plan.',
  '6. Require concrete verification of changed behavior. For code changes, obtain relevant test or inspection evidence before completion.',
  '7. Return complete only when durable outputs prove the original goal and its acceptance checks are satisfied.',
  '',
  'Do not return proceed: this autonomous workflow has no hidden static work after this gate.',
  'Do not ask the initiating user to construct JSON or choose agents.',
  'Do not propose pool, addDir, taskFile, shell authority, or unbounded work; Bullswarm owns routing and process authority.',
  'Treat maxAgents and maxWorkflowSeconds as planning targets, not hard stop conditions. Prefer an efficient plan near those targets, but exceed them rather than abandon already-started work or skip required verification.',
  'Return stop only for a concrete safety, authority, capability, dependency, or external blocker—not merely because an advisory target was reached.',
].join('\n');

function positiveInt(value, fallback, { min = 1, max = Number.MAX_SAFE_INTEGER } = {}) {
  if (value == null) return fallback;
  const parsed = Number(value);
  if (!Number.isInteger(parsed) || parsed < min || parsed > max) {
    throw new Error(`expected an integer from ${min} to ${max}, got "${value}"`);
  }
  return parsed;
}

export function buildGoalWorkflow({
  goal,
  cwd = process.cwd(),
  orchestrator = null,
  name = null,
  settings = {},
  worktreeIsolation = 'agent-decides',
} = {}) {
  if (typeof goal !== 'string' || !goal.trim()) {
    throw new Error('goal text is required');
  }
  if (orchestrator != null && (typeof orchestrator !== 'string' || !NAME_RE.test(orchestrator))) {
    throw new Error(`invalid orchestrator pool "${orchestrator}"`);
  }

  const targetDir = resolve(cwd);
  const workflowName = name ?? `goal-${Date.now().toString(36)}`;
  if (!NAME_RE.test(workflowName)) throw new Error(`invalid generated workflow name "${workflowName}"`);

  const maxAgents = positiveInt(settings.maxAgents, 30, { max: 500 });
  const maxExpansionRounds = positiveInt(settings.maxExpansionRounds, 8, { max: 50 });
  const maxActions = positiveInt(settings.maxActions, 40, { max: 1000 });
  const maxItemsPerExpansion = positiveInt(settings.maxItemsPerExpansion, 8, { max: 100 });
  const maxWorkflowSeconds = positiveInt(settings.maxWorkflowSeconds, 3600, { max: 86_400 });
  const concurrency = positiveInt(settings.concurrency, 3, { max: 16 });
  const retryAttempts = positiveInt(settings.retryAttempts, 1, { min: 0, max: 3 });
  if (!['agent-decides', 'off', 'required'].includes(worktreeIsolation)) {
    throw new Error(`invalid worktree isolation policy "${worktreeIsolation}"`);
  }
  const worktreeInstruction = worktreeIsolation === 'required'
    ? 'Worktree isolation policy: required when the selected agent supports it.'
    : worktreeIsolation === 'off'
      ? 'Worktree isolation policy: disabled; work in the supplied directory.'
      : 'Worktree isolation policy: agent decides whether isolation is useful; do not introduce a worktree for routine sequential work.';

  return {
    schemaVersion: 'bullswarm.workflow.v1',
    name: workflowName,
    mode: 'adaptive',
    description: 'Autonomous goal-driven workflow generated by Bullswarm.',
    intent: {
      goal: goal.trim(),
      cwd: targetDir,
      autonomous: true,
      requestedOrchestrator: orchestrator ?? 'auto',
      worktreeIsolation,
    },
    orchestration: {
      mode: 'autonomous',
      requestedPool: orchestrator ?? null,
      selection: orchestrator ? 'user-pinned-for-testing' : 'capability-strategy-and-quota',
      completionPolicy: {
        requireSuccessfulWorker: true,
        requireSuccessfulVerification: true,
      },
    },
    inputs: {},
    settings: {
      concurrency,
      retryAttempts,
      escalateOnFail: true,
      maxAgents,
      warnAtAgents: Math.min(20, maxAgents),
      maxExpansionRounds,
      maxActions,
      maxItemsPerExpansion,
      maxWorkflowSeconds,
    },
    phases: [{
      name: 'autonomous-delivery',
      steps: [{
        id: 'orchestrator',
        type: 'decide',
        ...(orchestrator ? { pool: orchestrator } : {}),
        lane: 'analyze',
        requiresCapabilities: ['strong-analysis', 'workflow-planning'],
        addDir: targetDir,
        actionDefaults: {
          lane: 'build',
          requiresCapabilities: ['code-reading', 'file-editing'],
          addDir: targetDir,
        },
        prompt: `${AUTONOMOUS_ORCHESTRATOR_PROMPT}\n\n${worktreeInstruction}`,
        onError: 'fail',
      }],
    }],
  };
}
